### PR TITLE
Reduce infinite sync requests.

### PR DESCRIPTION
**Pull request by nikunjkotecha**

### CODE REVIEW

**Comment by nikunjkotecha** [comment]
cc @sdelbosc

**Comment by sdelbosc** [comment]
@miromichalicka this one has been created to avoid infinite retries from ACM against Drupal. What we assume is that it fails during product update it is going to get caught and tracked on Drupal side with enough info to manually retry if needed.

**Comment by miromichalicka** [comment]
Ok, so do we need to return that at all then?

**Comment by sdelbosc** [comment]
I believe that if you don't return TRUE, ACM retries. Malachy may know a bit more.

**Comment by miromichalicka** [comment]
Yeah, but if we always return TRUE then middleware will never retry :) I'll talk with Malachy and come back about this one.

**Comment by sdelbosc** [comment]
If there is something that you don't catch or that fails during CSRF token acquisition, ACM would still retry

**Comment by miromichalicka** [comment]
AFAIK that would retry based on http response code.

**Pull request merged**
