### PR TITLE
Make field_configured_skus non translatable as it is global level att…

### PR DESCRIPTION
**Pull request by nikunjkotecha**
…ribute in MDC.

### CODE REVIEW

**Comment by nikunjkotecha** [comment]
cc @sdelbosc @vbouchet31

**Comment by miromichalicka** [comment]
This sounds like project specific issue.

**Comment by nikunjkotecha** [comment]
@miromichalicka link between children and parent is global level attribute, we can't have 5 variants in one store and 6 in another or different ones in different store. We can have different status (that too website level) per variant but not different variants itself.

cc @sdelbosc @vbouchet31

**Comment by nikunjkotecha** [comment]
@sdelbosc can you have discussion with @miromichalicka on this one?

**Comment by sdelbosc** [comment]
track it in the list of topics to discuss

**Pull request closed without merging**
