### PR TITLE
Use loadFromSku which has static cache.

### PR DESCRIPTION
**Pull request by nikunjkotecha**

### CODE REVIEW

**Comment by nikunjkotecha** [comment]
cc @sdelbosc @vbouchet31

**Comment by sdelbosc** [comment]
I think we should have a ticket to not forget testing

**Comment by nikunjkotecha** [comment]
@sdelbosc we are already testing this as part of a ticket right now

**Comment by sdelbosc** [comment]
My bad, thought I was on Alshaya repo

**Pull request merged**
