### PR TITLE
Add behat tests

### PR DESCRIPTION
**Pull request by miromichalicka**
In this PR we're adding a couple of Behat tests for cart and checkout with a config file.

### CODE REVIEW

**Comment by malachy-mcconnell** [comment]
This is spectacular.

**Comment by malachy-mcconnell** [comment]
The travis fail is due to PHPCS. Do you want to add `// phpcs:ignoreFile` to these files? I get the feeling Behat testing using a different pattern to Drupal core.

But I'm ready to merge this. I'm going to test it now but on code review it looks great.

**Comment by csibar** [comment]
Looks awesome!

**Comment by miromichalicka** [comment]
🎉

**Pull request merged**
