### PR TITLE
WIP: Deprecate SKUFieldsManager class.

### PR DESCRIPTION
**Pull request by miromichalicka**
```
a:4:{s:11:"deprecation";s:311:"EntityDefinitionUpdateManagerInterface::applyUpdates() is deprecated in 8.7.0 and will be removed before Drupal 9.0.0. Use \Drupal\Core\Entity\EntityDefinitionUpdateManagerInterface::getChangeList() and execute each entity type and field storage update manually instead. See https://www.drupal.org/node/3034742.";s:5:"class";s:51:"Drupal\Tests\acq_sku\Functional\CategoryManagerTest";s:6:"method";s:16:"testSyncCategory";s:15:"triggering_file";s:106:"/home/travis/build/acquia/orca-build/docroot/core/lib/Drupal/Core/Entity/EntityDefinitionUpdateManager.php";}
```

### CODE REVIEW

**Comment by nikunjkotecha** [comment]
@miromichalicka fix for this is in progress

**Comment by miromichalicka** [comment]
Hopefully coming soon. TBH I don't know why we need this one, if you can achieve the same by update hooks.

**Comment by nikunjkotecha** [comment]
It is just to help reduce code in update hooks (there is still more code generalisation possible) and to make the field definitions uniform. If we do all these in update hooks only it will become hard to maintain consistency.

Also, config (sku_base_fields) helps reduce lot of conditions and checks in code, automate facets creation (we had mix of facets created some with underscore, some without underscore, some with prefix, some without prefix) which triggered the need to have consistency.

**Comment by gupta-ashutosh5** [comment]
@nikunjkotecha applied the fix for applyUpdates() issue in PR https://github.com/acquia/acquia_commercemanager/pull/162. Please review.

**Pull request closed without merging**
