### PR TITLE
[WIP] Make sync logs report friendly.

### PR DESCRIPTION
**Pull request by nikunjkotecha**

### CODE REVIEW

**Comment by nikunjkotecha** [comment]
cc @sdelbosc

**Comment by nikunjkotecha** [comment]
@sdelbosc PR updated with latest changes in project.

**Comment by miromichalicka** [comment]
@nikunjkotecha this ticket is marked as DNM, should we expect any extra work?

**Comment by nikunjkotecha** [comment]
@miromichalicka yes, can you review https://www.drupal.org/project/log_entity_operations once to see if it will make things better? It is a low priority task right now to do it globally for all entity types.

cc @sdelbosc @vbouchet31

**Comment by miromichalicka** [comment]
Closing this PR for now, feel free to reopen once it's ready for merging.

**Pull request closed without merging**
