### PR TITLE
Not sync skus for catalog promotion on promotion sync.

### PR DESCRIPTION
**Pull request by joshirohit100**
Should be handled at magento level for consistency.

Related magento PR - https://github.com/acquia/commerce-manager-magento/pull/36

### CODE REVIEW

**Comment by joshirohit100** [comment]
cc @sdelbosc

**Comment by malachy-mcconnell** [comment]
I agree this is not the place to try to initiate a product synchronisation. I'm happy to discuss better ways to proceed.

**Comment by joshirohit100** [comment]
We are trying from here - https://github.com/acquia/commerce-manager-magento/pull/36

**Comment by malachy-mcconnell** [comment]
Aha. Thank you. I understand now. I like your approach.

**Pull request merged**
