### PR TITLE
Make code more re-usable for downloading images and delete them when SKU deleted.

### PR DESCRIPTION
**Pull request by nikunjkotecha**
Delete images when deleting SKU.
Allow additional base fields label to be translatable.

### CODE REVIEW

**Comment by nikunjkotecha** [comment]
related to https://github.com/acquia/commerce-manager-magento/pull/35

**Comment by nikunjkotecha** [comment]
cc @sdelbosc @vbouchet31

**Comment by malachy-mcconnell** [comment]
Added label 'do not merge' while we discuss the addition of this feature and the additional code needed to fully integrate swatch images into Commerce Manager.

**Comment by nikunjkotecha** [comment]
@miromichalicka @malachy-mcconnell @sdelbosc 

PR is updated now to fix some of the issues and make code more re-usable.
Fixes:
* Delete the image on delete of SKU
* Make the field label translatable in baseFieldDefinitions

Once this is merged I'll create PR for swatch related changes which can stay as just a PR for long

**Pull request merged**
