### PR TITLE
Multiple fixes for configurable products.

### PR DESCRIPTION
**Pull request by nikunjkotecha**
Allow adding item to cart with multiple parents.
Remove obsolete code related to stock rework.
Update code to handle product tree, make it fast, efficient and less memory consuming.

### CODE REVIEW

**Review by miromichalicka — CHANGES_REQUESTED** [review]
This code changes a lot of functionality and has zero test coverage.

**Comment by nikunjkotecha** [comment]
@miromichalicka there are no tests as of now at all for any product except simple, can we aim that as separate PR or is it required must for this one?

**Comment by miromichalicka** [comment]
@nikunjkotecha lately there were couple fixes of fixes so we would like to avoid this and we would like to have tests as part of every pr.

**Comment by nikunjkotecha** [comment]
ok, I'll add tests - that might take time considering current priorities.

**Comment by miromichalicka** [comment]
@nikunjkotecha any progress on those tests?

**Comment by nikunjkotecha** [comment]
not yet, I'll spend sometime tomorrow and get it there. This tasks were moved to lower priority :(

**Comment by nikunjkotecha** [comment]
BTW I've more performance updates for deriveProductTree, I'll also add that to PR

**Comment by miromichalicka** [comment]
No progress in the last 14 days, please reopen when ready.

**Comment by nikunjkotecha** [comment]
@miromichalicka 
Update: I spend sometime during the weekend to get configurable products and it's tests  work, i'm finally stuck at following, I'll raise fresh PR in this week and that will need to be reviewed freshly as there are some fixes required in code to make it work first

Error I'm stuck at now:
```
Schema errors for acm_sku.configurable_form_settings with the following errors: acm_sku.configurable_form_settings:attribute_weights.default.color missing schema
```

**Comment by nikunjkotecha** [comment]
@miromichalicka created #158 

cc @vbouchet31 @sdelbosc

**Pull request closed without merging**
