### PR TITLE
[DNM] Use persistent locks to avoid issues.

### PR DESCRIPTION
**Pull request by nikunjkotecha**
https://www.drupal.org/project/memcache/issues/3020060

### CODE REVIEW

**Comment by nikunjkotecha** [comment]
cc @sdelbosc @vbouchet31

**Comment by nikunjkotecha** [comment]
@miromichalicka just curios, any reason to not do this change? we are using this in the project.

cc @sdelbosc

**Comment by nikunjkotecha** [comment]
@sdelbosc we will need to think of this one, it will revert the fixes that we have.

**Comment by sdelbosc** [comment]
track this in the ticket

**Pull request closed without merging**
