### PR TITLE
Refactor how we add/update/delete base fields in SKU.

### PR DESCRIPTION
**Pull request by nikunjkotecha**
* Move procedural acm_sku_add_base_fields() to service
* No need to have all the fields passed to new service function now, only the fields which are not the same as default values must be passed
* All the fields are now gather through alter hook, allowing custom modules to change based on needs - better support for factory sites/approach
* [New] Provides service function to get all current additions
* [New] Provides a way to hook into the fields addition process and take actions (for instance adding a facet and facet block for a field)
* [New] Provides a way to remove a base field and hook into the removal process
* [New] For any reason if a field code gets changed on remote system and we don't want to change the structure in Drupal, we can update the source of the field and it will read from source instead of using field_code in the attribute/extension (again better support for factory sites/approach)

### CODE REVIEW

**Comment by nikunjkotecha** [comment]
cc @sdelbosc @vbouchet31

**Comment by miromichalicka** [comment]
@nikunjkotecha @sdelbosc This is not refactoring and it's not following backward compatibility. It also has no test coverage and the pull request doesn't have any description.

**Comment by nikunjkotecha** [comment]
@miromichalicka you are right about comment. Will try to summarise the changes soon, need of it and whats new.

About backwards compatibility - this is actually not changing structure of config or fields array used previously, it is adding some new fields in the array.

And previously it was a procedural function in module and now it is a service.

There is some change required in code/format only when we want to add new field now, existing fields added in the config `acq_sku.base_field_additions` OR `acm_sku.base_field_additions` will keep working as is, no impact - verified that on existing live sites.

**Comment by nikunjkotecha** [comment]
fixed conflicts

**Comment by nikunjkotecha** [comment]
@miromichalicka thanks for merging this one, I'll try and create tests for the feature (add custom base fields to SKU via the service, created public ticket for the same

https://github.com/acquia/commerce-manager/issues/124

**Pull request merged**
